export const about = {
  en: {
    crumb: "About",
    hero: {
      title: ["The story", "behind", "Natwan."],
      lede: "Not merely a name — but a *philosophy* upon which an entire entity is built. Founded in 2007, Natwan Group is a diversified investment holding shaped by patience, discipline, and a quiet refusal to compromise on what matters.",
      meta: [
        { label: "Founded", value: "2007" },
        { label: "Years Operating", value: "18+" },
        { label: "Sectors", value: "5 Active" },
        { label: "Headquarters", value: "Dammam, KSA" },
      ],
    },
    story: {
      bannerQuote: '"Like mountains, we are built to stand — through cycles, through transformation, through time."',
      bannerTag: "FIG. 01\nFOUNDATION",
      markerNum: "01",
      markerLabel: "Our Story",
      heading: "Born of the *mountains.*\nBuilt for the long view.",
      asideQuote: '"In a world where business accelerates and standards shift, the strongest entities are those founded on something immovable."',
      lead: "The name *Natwan* draws from mountain ranges that symbolise steadiness, strength, and continuity. As mountains stand against the elements, Natwan stands as a partner you can depend on — balancing clear vision with precise execution to create real, sustainable value.",
      para2: "Natwan Group was founded in 2007 with a clear conviction: that the strongest businesses are those built on patience, discipline, and a long-term view. In a market that often rewards speed over substance, we chose to build differently — methodically, deliberately, and with an unwavering commitment to quality.",
      nameMeaning: {
        label: "— On the Name",
        word: "Natwan",
        pron: "/nat·wan/",
        desc: "Drawn from the Arabic word for mountain ranges, *Natwan* evokes the qualities that anchor our identity: permanence, elevation, and the kind of strength that endures across cycles, weather, and time.",
      },
      para3: "From the beginning, our work has been guided by a clear methodology — one that begins with rigorous analysis, moves through careful planning, and ends with execution to the highest professional standard. We do not improvise our way to results; we engineer them, deliberately and patiently, across every engagement we take on.",
      inlineCaption: "FIG. 02 — METHOD",
      para4: "Today, Natwan Group operates across five integrated sectors — contracting, hospitality, real estate, advisory, and asset management — designed to compound capability rather than fragment it. Each sector strengthens the others, creating an ecosystem of expertise that few standalone firms can match.",
      para5: "Our success is measured not by the number of projects launched, but by the durability of what we leave behind. We build for decades, not quarters — because that is what the people who place their trust in us deserve.",
    },
    timeline: {
      markerNum: "02",
      markerLabel: "Our Journey",
      heading: "Eighteen years.\n*One continuous ascent.*",
      aside: "From foundation in 2007 to today, every step has been deliberate — building capability, deepening expertise, and expanding into sectors where we can create durable value.",
      events: [
        { year: "2007", title: "Foundation", desc: "Natwan Group is established in Dammam with a focus on contracting and real estate development." },
        { year: "2012", title: "Hospitality Expansion", desc: "Entry into hospitality and hotel apartment development, broadening the group's operating footprint." },
        { year: "2016", title: "Advisory Launch", desc: "Establishment of the advisory and business management arm to serve enterprise clients." },
        { year: "2019", title: "Asset Management", desc: "Launch of dedicated asset and investment management capability for long-term portfolios." },
        { year: "2022", title: "Vision 2030 Alignment", desc: "Strategic alignment of group investments with the Kingdom's transformation goals." },
        { year: "2025", title: "Today & Onward", desc: "Operating across five integrated sectors with a clear focus on the next decade of compound growth." },
      ],
    },
    vm: {
      markerNum: "03",
      markerLabel: "Vision & Mission",
      heading: "We know *where* we are going.\nAnd *how* we will arrive.",
      cards: [
        {
          image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85",
          label: "Our Vision",
          title: "To be the leading *regional* investment holding.",
          quote: '"To compound trust into capability — and capability into lasting outcomes."',
          body: "To be among the leading regional investment holdings — built on innovation, sustainability, and the capacity to scale. We aspire to be the first choice for those seeking a partner that combines trust, quality, and measurable results — and to leave a clear mark across the sectors in which we operate.",
        },
        {
          image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85",
          label: "Our Mission",
          title: "To deliver *integrated* solutions of lasting quality.",
          quote: '"Our vision guides us. Our mission carries us there."',
          body: "We are committed to delivering integrated, high-quality solutions grounded in a deep understanding of our clients' needs and a strategic vision that ensures their objectives are achieved with precision. We build long-term partnerships through professionalism, discipline, and commitment — always pursuing added value that exceeds expectations.",
        },
      ],
    },
    valuesDeep: {
      markerNum: "04",
      markerLabel: "Our Values",
      heading: "Not principles we declare.\n*Standards we operate by.*",
      intro: "Five values that govern every decision we make — from how we evaluate opportunities, to how we deliver on commitments, to how we treat the people who place their trust in us. They are not aspirational; they are operational, and they show up in the work.",
      items: [
        { num: "01.", title: "Excellence", tagline: '"The highest standard, applied consistently."', desc: 'We do not aim for "acceptable." We aim for the highest professional standard in every project, every engagement, every decision — because excellence is what compounds into reputation, and reputation is what compounds into trust.', image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
        { num: "02.", title: "Integrity", tagline: '"Trust earned through transparency."', desc: "Our word is our work. We are direct with our clients, transparent with our partners, and consistent in what we say and what we do. Integrity is not a marketing claim — it is the foundation of every long-term relationship we have built.", image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
        { num: "03.", title: "Innovation", tagline: '"Solutions that move with the market."', desc: "Markets evolve. Standards shift. Opportunities emerge. We invest in staying ahead — through continuous learning, market intelligence, and a willingness to question how we have always done things in pursuit of how things can be done better.", image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
        { num: "04.", title: "Commitment", tagline: '"Promises kept with precision."', desc: "When we commit, we deliver. Not approximately. Not eventually. Precisely, and on time. This discipline is the difference between a partner and a vendor — and it is the standard we hold ourselves to without exception.", image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
        { num: "05.", title: "Partnership", tagline: '"Relationships designed to last."', desc: "We do not pursue transactions. We build partnerships — relationships where mutual success is the only acceptable outcome, where trust deepens with time, and where every engagement opens the door to the next.", image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
      ],
    },
    approach: {
      bannerQuote: '"Methodology is not bureaucracy — it is the difference between aspiration and outcome."',
      bannerTag: "FIG. 03\nMETHODOLOGY",
      markerNum: "05",
      markerLabel: "Our Approach",
      heading: "Every step measured.\n*Every outcome earned.*",
      aside: "A repeatable, disciplined methodology applied across every engagement — from contracting projects to advisory mandates. The difference between aspiration and outcome.",
      steps: [
        { num: "01.", title: "Analyse", desc: "We start by understanding the client's needs and surrounding market context with precision and patience." },
        { num: "02.", title: "Strategise", desc: "A clear plan built on objectives that are ambitious, measurable, and genuinely reachable." },
        { num: "03.", title: "Execute", desc: "Projects delivered to the highest professional standards — methodically, on time, without compromise." },
        { num: "04.", title: "Refine", desc: "Continuous performance monitoring and refinement as the engagement progresses through its phases." },
        { num: "05.", title: "Endure", desc: "Outcomes designed to compound and last — not merely to launch, announce, and move on." },
      ],
    },
    chairman: {
      markerNum: "06",
      markerLabel: "Chairman's Message",
      portraitTag: "— Chairman's Office",
      heading: "A vision that *inspires.*\nLeadership that delivers.",
      quotes: [
        '"We built Natwan on foundations that combine *strategic clarity* with *professional execution* — a model that reflects quality, trust, and sustainability across everything we do."',
        '"Our work is shaped by patience, our standards by experience, and our partnerships by the conviction that lasting value is earned — never promised."',
      ],
      sigName: "[ Chairman's Name ]",
      sigTitle: "Chairman of the Board · Natwan Group",
    },
    numbers: {
      markerNum: "07",
      markerLabel: "By the Numbers",
      heading: "Years compound.\n*So do outcomes.*",
      cells: [
        { label: "Established", num: "2007", symbol: "", desc: "The year Natwan Group was founded in Dammam, KSA." },
        { label: "Years Operating", num: "18", symbol: "+", desc: "Of compound experience across complete economic cycles." },
        { label: "Active Sectors", num: "05", symbol: "", desc: "Integrated sectors operating under one philosophy." },
        { label: "Vision Horizon", num: "2030", symbol: "", desc: "Aligned with the goals of the Kingdom's strategic vision." },
      ],
    },
    cta: {
      eyebrow: "BEGIN A CONVERSATION",
      heading: "Let's build something\n*that lasts.*",
      body: "Whether you're exploring a partnership, an investment opportunity, or a service engagement — we would be glad to start the conversation.",
      primary: "Schedule a Meeting",
      secondary: "Explore Our Sectors",
    },
  },

  ar: {
    crumb: "من نحن",
    hero: {
      title: ["القصة", "وراء", "نطوان."],
      lede: "ليست مجرّد اسم — بل *فلسفة* يُبنى عليها كيانٌ بأكمله. تأسست مجموعة نطوان عام 2007 كشركة قابضة استثمارية متنوّعة، صاغها الصبر والانضباط ورفضٌ هادئ للتنازل عمّا يهمّ.",
      meta: [
        { label: "التأسيس", value: "2007" },
        { label: "أعوام العمل", value: "18+" },
        { label: "القطاعات", value: "5 نشطة" },
        { label: "المقر الرئيسي", value: "الدمام، السعودية" },
      ],
    },
    story: {
      bannerQuote: "«كالجبال، خُلقنا لنصمد — عبر الدورات، وعبر التحوّلات، وعبر الزمن.»",
      bannerTag: "شكل 01\nالأساس",
      markerNum: "01",
      markerLabel: "قصّتنا",
      heading: "وُلدنا من *الجبال.*\nوبُنينا للنظرة البعيدة.",
      asideQuote: "«في عالمٍ تتسارع فيه الأعمال وتتبدّل المعايير، أقوى الكيانات هي تلك المؤسَّسة على شيءٍ راسخ لا يتزحزح.»",
      lead: "يُستمدّ اسم *نطوان* من سلاسل الجبال التي ترمز إلى الثبات والقوة والاستمرارية. وكما تصمد الجبال أمام العوامل، تقف نطوان شريكاً يُعتمَد عليه — يوازن بين الرؤية الواضحة والتنفيذ الدقيق لخلق قيمة حقيقية ومستدامة.",
      para2: "تأسست مجموعة نطوان عام 2007 بقناعة واضحة: أن أقوى الأعمال هي تلك المبنيّة على الصبر والانضباط والنظرة طويلة الأمد. وفي سوقٍ كثيراً ما يكافئ السرعة على حساب الجوهر، اخترنا أن نبني بشكلٍ مختلف — بمنهجية وتأنٍّ والتزامٍ راسخ بالجودة.",
      nameMeaning: {
        label: "— عن الاسم",
        word: "نطوان",
        pron: "/نَطْوان/",
        desc: "مستمدٌّ من الكلمة العربية الدالّة على سلاسل الجبال، يستحضر *نطوان* الصفات التي ترسّخ هويتنا: الرسوخ، والارتفاع، وذلك النوع من القوة الذي يدوم عبر الدورات والأحوال والزمن.",
      },
      para3: "منذ البداية، اهتدى عملنا بمنهجية واضحة — تبدأ بتحليل دقيق، وتمرّ بتخطيطٍ متأنٍّ، وتنتهي بتنفيذٍ وفق أعلى معيارٍ مهني. نحن لا نرتجل طريقنا إلى النتائج؛ بل نهندسها، بتأنٍّ وعمدٍ، في كل ارتباطٍ نتولّاه.",
      inlineCaption: "شكل 02 — المنهج",
      para4: "اليوم، تعمل مجموعة نطوان عبر خمسة قطاعات متكاملة — المقاولات والضيافة والعقارات والاستشارات وإدارة الأصول — مصمّمة لتراكم القدرات بدلاً من تشتيتها. يعزّز كل قطاع الآخر، فينشأ نظامٌ من الخبرة يصعب على الشركات المنفردة مضاهاته.",
      para5: "لا يُقاس نجاحنا بعدد المشاريع المُطلَقة، بل بمتانة ما نتركه خلفنا. نبني لعقودٍ لا لأرباع سنوية — لأن هذا ما يستحقّه من وضعوا ثقتهم فينا.",
    },
    timeline: {
      markerNum: "02",
      markerLabel: "مسيرتنا",
      heading: "ثمانية عشر عاماً.\n*صعودٌ متّصلٌ واحد.*",
      aside: "من التأسيس عام 2007 حتى اليوم، كانت كل خطوة مقصودة — بناءً للقدرات، وتعميقاً للخبرة، وتوسّعاً في قطاعات يمكننا أن نخلق فيها قيمة دائمة.",
      events: [
        { year: "2007", title: "التأسيس", desc: "تأسيس مجموعة نطوان في الدمام مع التركيز على المقاولات والتطوير العقاري." },
        { year: "2012", title: "التوسّع في الضيافة", desc: "الدخول في تطوير الضيافة والشقق الفندقية، توسيعاً لنطاق عمل المجموعة." },
        { year: "2016", title: "إطلاق الاستشارات", desc: "تأسيس ذراع الاستشارات وإدارة الأعمال لخدمة عملاء المؤسسات." },
        { year: "2019", title: "إدارة الأصول", desc: "إطلاق قدرة مخصّصة لإدارة الأصول والاستثمار للمحافظ طويلة الأمد." },
        { year: "2022", title: "التوافق مع رؤية 2030", desc: "مواءمة استراتيجية لاستثمارات المجموعة مع أهداف تحوّل المملكة." },
        { year: "2025", title: "اليوم وما بعده", desc: "العمل عبر خمسة قطاعات متكاملة مع تركيزٍ واضح على عقدٍ قادم من النمو التراكمي." },
      ],
    },
    vm: {
      markerNum: "03",
      markerLabel: "الرؤية والرسالة",
      heading: "نعرف *إلى أين* نمضي.\nو*كيف* سنصل.",
      cards: [
        {
          image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85",
          label: "رؤيتنا",
          title: "أن نكون الشركة القابضة الاستثمارية *الإقليمية* الرائدة.",
          quote: "«أن نُراكم الثقة إلى قدرة — والقدرة إلى نتائج تدوم.»",
          body: "أن نكون من بين الشركات القابضة الاستثمارية الإقليمية الرائدة — مبنيّةً على الابتكار والاستدامة والقدرة على التوسّع. ونطمح أن نكون الخيار الأول لمن يبحث عن شريكٍ يجمع الثقة والجودة والنتائج القابلة للقياس — وأن نترك أثراً واضحاً في القطاعات التي نعمل بها.",
        },
        {
          image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85",
          label: "رسالتنا",
          title: "أن نقدّم حلولاً *متكاملة* بجودةٍ تدوم.",
          quote: "«رؤيتنا تهدينا. ورسالتنا توصلنا.»",
          body: "نلتزم بتقديم حلول متكاملة عالية الجودة، مبنيّة على فهمٍ عميق لاحتياجات عملائنا ورؤيةٍ استراتيجية تضمن تحقيق أهدافهم بدقّة. نبني شراكات طويلة الأمد عبر الاحترافية والانضباط والالتزام — ساعين دوماً إلى قيمةٍ مضافة تفوق التوقّعات.",
        },
      ],
    },
    valuesDeep: {
      markerNum: "04",
      markerLabel: "قيمنا",
      heading: "ليست مبادئ نعلنها.\n*بل معايير نعمل بها.*",
      intro: "خمس قيم تحكم كل قرار نتخذه — من كيفية تقييمنا للفرص، إلى كيفية وفائنا بالتزاماتنا، إلى كيفية تعاملنا مع من يضعون ثقتهم فينا. إنها ليست طموحات؛ بل ممارسات تشغيلية تظهر في العمل.",
      items: [
        { num: "01.", title: "التميّز", tagline: "«أعلى معيار، يُطبَّق باتساق.»", desc: "لا نسعى إلى «المقبول». بل نسعى إلى أعلى معيارٍ مهني في كل مشروع وكل ارتباط وكل قرار — لأن التميّز هو ما يتراكم إلى سمعة، والسمعة هي ما يتراكم إلى ثقة.", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
        { num: "02.", title: "النزاهة", tagline: "«ثقةٌ تُكتسَب بالشفافية.»", desc: "كلمتنا هي عملنا. نحن صرحاء مع عملائنا، وشفّافون مع شركائنا، ومتّسقون فيما نقول وما نفعل. النزاهة ليست شعاراً تسويقياً — بل أساس كل علاقة طويلة الأمد بنيناها.", image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
        { num: "03.", title: "الابتكار", tagline: "«حلولٌ تتحرّك مع السوق.»", desc: "الأسواق تتطوّر. المعايير تتبدّل. الفرص تظهر. نستثمر في البقاء في المقدّمة — عبر التعلّم المستمر، وذكاء السوق، والاستعداد لمساءلة طريقتنا المعتادة سعياً لطريقةٍ أفضل.", image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
        { num: "04.", title: "الالتزام", tagline: "«وعودٌ تُنجَز بدقّة.»", desc: "حين نلتزم، ننجز. لا تقريباً. ولا في وقتٍ لاحق. بل بدقّة وفي الموعد. هذا الانضباط هو الفارق بين شريكٍ ومورّد — وهو المعيار الذي نلزم به أنفسنا دون استثناء.", image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
        { num: "05.", title: "الشراكة", tagline: "«علاقاتٌ مصمّمة لتدوم.»", desc: "لا نسعى وراء الصفقات. بل نبني شراكات — علاقات يكون فيها النجاح المتبادل هو النتيجة الوحيدة المقبولة، وتتعمّق فيها الثقة مع الزمن، ويفتح كل ارتباطٍ فيها الباب لما بعده.", image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=85" },
      ],
    },
    approach: {
      bannerQuote: "«المنهجية ليست بيروقراطية — إنها الفارق بين الطموح والنتيجة.»",
      bannerTag: "شكل 03\nالمنهجية",
      markerNum: "05",
      markerLabel: "نهجنا",
      heading: "كل خطوة مدروسة.\n*وكل نتيجة مستحَقّة.*",
      aside: "منهجية منضبطة قابلة للتكرار تُطبَّق في كل ارتباط — من مشاريع المقاولات إلى مهام الاستشارات. إنها الفارق بين الطموح والنتيجة.",
      steps: [
        { num: "01.", title: "التحليل", desc: "نبدأ بفهم احتياجات العميل وسياق السوق المحيط بدقّة وصبر." },
        { num: "02.", title: "وضع الاستراتيجية", desc: "خطة واضحة مبنيّة على أهداف طموحة وقابلة للقياس والتحقيق فعلاً." },
        { num: "03.", title: "التنفيذ", desc: "مشاريع تُنجَز وفق أعلى المعايير المهنية — بمنهجية وفي الوقت ودون تنازل." },
        { num: "04.", title: "التحسين", desc: "مراقبة مستمرة للأداء وتحسينه مع تقدّم العمل عبر مراحله." },
        { num: "05.", title: "الاستدامة", desc: "نتائج صُمّمت لتتراكم وتدوم — لا لمجرّد الإطلاق والإعلان والمضيّ." },
      ],
    },
    chairman: {
      markerNum: "06",
      markerLabel: "كلمة رئيس مجلس الإدارة",
      portraitTag: "— مكتب رئيس مجلس الإدارة",
      heading: "رؤيةٌ *تُلهِم.*\nوقيادةٌ تُنجِز.",
      quotes: [
        "«بنينا نطوان على أسسٍ تجمع *الوضوح الاستراتيجي* مع *التنفيذ المهني* — نموذج يعكس الجودة والثقة والاستدامة في كل ما نقوم به.»",
        "«عملنا يصوغه الصبر، ومعاييرنا تصوغها الخبرة، وشراكاتنا يصوغها الإيمان بأن القيمة الدائمة تُكتسَب — ولا يُوعَد بها.»",
      ],
      sigName: "[ اسم رئيس مجلس الإدارة ]",
      sigTitle: "رئيس مجلس الإدارة · مجموعة نطوان",
    },
    numbers: {
      markerNum: "07",
      markerLabel: "بالأرقام",
      heading: "الأعوام تتراكم.\n*وكذلك النتائج.*",
      cells: [
        { label: "التأسيس", num: "2007", symbol: "", desc: "العام الذي تأسست فيه مجموعة نطوان في الدمام، السعودية." },
        { label: "أعوام العمل", num: "18", symbol: "+", desc: "من الخبرة التراكمية عبر دورات اقتصادية كاملة." },
        { label: "القطاعات النشطة", num: "05", symbol: "", desc: "قطاعات متكاملة تعمل وفق فلسفة واحدة." },
        { label: "أفق الرؤية", num: "2030", symbol: "", desc: "متوائمة مع أهداف رؤية المملكة الاستراتيجية." },
      ],
    },
    cta: {
      eyebrow: "ابدأ حواراً",
      heading: "لنبنِ شيئاً\n*يدوم.*",
      body: "سواء كنت تستكشف شراكة، أو فرصة استثمارية، أو ارتباط خدمة — يسعدنا أن نبدأ الحوار.",
      primary: "احجز اجتماعاً",
      secondary: "استكشف قطاعاتنا",
    },
  },
};
