export const contact = {
  en: {
    crumb: "Contact",
    hero: {
      eyebrow: "◆ GET IN TOUCH",
      title: ["We are here.", "*To begin with you.*"],
      lede: "Whether you're exploring a partnership, an investment opportunity, or a service engagement — we would be glad to start the conversation.",
      asideTag: "NATWAN GROUP\n*— EST. 2007*\nRIYADH, KSA",
    },
    main: {
      label: "— Direct Contact",
      heading: "Reach us through\n*any channel.*",
      body: "Our team handles every enquiry — from new project conversations to ongoing partnerships. Choose the channel that suits you, and we'll respond within one business day.",
      channels: [
        { icon: "address", label: "Address", value: "Natwan Suites — Abha, 'Asir Region, KSA", arrow: true, href: "https://maps.app.goo.gl/T5mcAuFWRcniSECA9", external: true },
        { icon: "phone", label: "Phone", value: "+966 54 200 8206", arrow: true, href: "tel:+966542008206" },
        { icon: "whatsapp", label: "WhatsApp", value: "+966 54 200 8206", arrow: true, href: "https://wa.me/966542008206", external: true },
        { icon: "email", label: "Email", value: "info@natwanco.com", arrow: true, href: "mailto:info@natwanco.com" },
        { icon: "clock", label: "Office Hours", value: "Sun – Thu · 09:00 – 17:00 AST" },
      ],
    },
    form: {
      label: "— Send a Message",
      heading: "Let's start\na *conversation.*",
      intro: "Fill in the form below and a member of our team will respond within one business day.",
      fields: {
        name: { label: "Full Name", ph: "Your name" },
        email: { label: "Email Address", ph: "you@company.com" },
        phone: { label: "Phone Number", ph: "Optional" },
        subject: { label: "Subject", ph: "Select a topic" },
        message: { label: "Your Message", ph: "Tell us about your project, partnership opportunity, or enquiry…" },
      },
      subjects: [
        { value: "contracting", label: "Contracting" },
        { value: "hospitality", label: "Hospitality" },
        { value: "real-estate", label: "Real Estate Development" },
        { value: "advisory", label: "Advisory" },
        { value: "asset-management", label: "Asset Management" },
        { value: "other", label: "Other" },
      ],
      note: "— We respond within\none business day.",
      submit: "Send Message",
      alert: "Form ready — connect to your backend or email service.",
    },
    map: {
      label: "— Visit Our Office",
      heading: "Find us in *Abha.*",
      aside: "Natwan Suites in Abha — set in the highlands of the 'Asir region, where our standard of hospitality meets the south of the Kingdom.",
      embedSrc: "https://maps.google.com/maps?q=18.2833335,42.6051029&z=16&output=embed",
      url: "https://maps.app.goo.gl/T5mcAuFWRcniSECA9",
      cta: "View on Google Maps",
      pinAccent: "NATWAN SUITES",
      pinLine: "Abha, KSA",
      overlayLabel: "— Office Location",
      overlayValue: "Natwan Suites — Abha, 'Asir Region",
      footerAccent: "— COORDINATES",
      footerCoord: "18.2833° N · 42.6051° E",
      footerTz: "GMT+3 · ARABIAN STANDARD TIME",
    },
    quick: {
      eyebrow: "DIRECT CHANNELS",
      heading: "Or reach us *instantly.*",
      body: "For faster conversations, use one of our direct channels — we'd be glad to hear from you.",
      cards: [
        { icon: "phone", label: "— Channel 01", title: "Direct Call", value: "+966 54 200 8206", href: "tel:+966542008206" },
        { icon: "whatsapp", label: "— Channel 02", title: "WhatsApp", value: "+966 54 200 8206", href: "https://wa.me/966542008206", external: true },
        { icon: "email", label: "— Channel 03", title: "Email Us", value: "info@natwanco.com", href: "mailto:info@natwanco.com" },
      ],
    },
    closing: {
      heading: "We're here.\n*To begin with you.*",
      body: "Every great partnership starts with a single conversation.",
    },
  },

  ar: {
    crumb: "تواصل معنا",
    hero: {
      eyebrow: "◆ ابقَ على تواصل",
      title: ["نحن هنا.", "*لنبدأ معك.*"],
      lede: "سواء كنت تستكشف شراكة، أو فرصة استثمارية، أو ارتباط خدمة — يسعدنا أن نبدأ الحوار.",
      asideTag: "مجموعة نطوان\n*— تأسست 2007*\nالرياض، السعودية",
    },
    main: {
      label: "— تواصل مباشر",
      heading: "تواصل معنا عبر\n*أي قناة.*",
      body: "يتولّى فريقنا كل استفسار — من حوارات المشاريع الجديدة إلى الشراكات المستمرة. اختر القناة التي تناسبك، وسنردّ خلال يوم عمل واحد.",
      channels: [
        { icon: "address", label: "العنوان", value: "أجنحة نطوان — أبها، منطقة عسير، السعودية", arrow: true, href: "https://maps.app.goo.gl/T5mcAuFWRcniSECA9", external: true },
        { icon: "phone", label: "الهاتف", value: "+966 54 200 8206", arrow: true, href: "tel:+966542008206" },
        { icon: "whatsapp", label: "واتساب", value: "+966 54 200 8206", arrow: true, href: "https://wa.me/966542008206", external: true },
        { icon: "email", label: "البريد الإلكتروني", value: "info@natwanco.com", arrow: true, href: "mailto:info@natwanco.com" },
        { icon: "clock", label: "ساعات العمل", value: "الأحد – الخميس · 09:00 – 17:00 بتوقيت السعودية" },
      ],
    },
    form: {
      label: "— أرسل رسالة",
      heading: "لنبدأ\n*حواراً.*",
      intro: "املأ النموذج أدناه وسيردّ عليك أحد أعضاء فريقنا خلال يوم عمل واحد.",
      fields: {
        name: { label: "الاسم الكامل", ph: "اسمك" },
        email: { label: "البريد الإلكتروني", ph: "you@company.com" },
        phone: { label: "رقم الهاتف", ph: "اختياري" },
        subject: { label: "الموضوع", ph: "اختر موضوعاً" },
        message: { label: "رسالتك", ph: "أخبرنا عن مشروعك أو فرصة الشراكة أو استفسارك…" },
      },
      subjects: [
        { value: "contracting", label: "المقاولات" },
        { value: "hospitality", label: "الضيافة" },
        { value: "real-estate", label: "التطوير العقاري" },
        { value: "advisory", label: "الاستشارات" },
        { value: "asset-management", label: "إدارة الأصول" },
        { value: "other", label: "أخرى" },
      ],
      note: "— نردّ خلال\nيوم عمل واحد.",
      submit: "إرسال الرسالة",
      alert: "النموذج جاهز — اربطه بخادمك أو بخدمة بريد إلكتروني.",
    },
    map: {
      label: "— زر مكتبنا",
      heading: "تجدنا في *أبها.*",
      aside: "أجنحة نطوان في أبها — بين مرتفعات منطقة عسير، حيث يلتقي معيارنا في الضيافة بجنوب المملكة.",
      embedSrc: "https://maps.google.com/maps?q=18.2833335,42.6051029&z=16&output=embed",
      url: "https://maps.app.goo.gl/T5mcAuFWRcniSECA9",
      cta: "افتح في خرائط جوجل",
      pinAccent: "أجنحة نطوان",
      pinLine: "أبها، السعودية",
      overlayLabel: "— موقع المكتب",
      overlayValue: "أجنحة نطوان — أبها، منطقة عسير",
      footerAccent: "— الإحداثيات",
      footerCoord: "18.2833° شمالاً · 42.6051° شرقاً",
      footerTz: "غرينتش+3 · التوقيت العربي القياسي",
    },
    quick: {
      eyebrow: "قنوات مباشرة",
      heading: "أو تواصل معنا *فوراً.*",
      body: "لحوارات أسرع، استخدم إحدى قنواتنا المباشرة — يسعدنا أن نسمع منك.",
      cards: [
        { icon: "phone", label: "— القناة 01", title: "اتصال مباشر", value: "+966 54 200 8206", href: "tel:+966542008206" },
        { icon: "whatsapp", label: "— القناة 02", title: "واتساب", value: "+966 54 200 8206", href: "https://wa.me/966542008206", external: true },
        { icon: "email", label: "— القناة 03", title: "راسلنا", value: "info@natwanco.com", href: "mailto:info@natwanco.com" },
      ],
    },
    closing: {
      heading: "نحن هنا.\n*لنبدأ معك.*",
      body: "كل شراكة عظيمة تبدأ بحوارٍ واحد.",
    },
  },
};
