// Home page content (EN + AR). Inline emphasis uses *stars*; \n is a line break.
import assetManagementImage from "../images/natwan projects/IMG-20240218-WA0135.jpg";

export const home = {
  en: {
    hero: {
      eyebrow: "A DIVERSIFIED INVESTMENT HOLDING · EST. 2007",
      title: ["We build", "what", "endures."],
      lede: "Natwan Group operates across five integrated sectors — contracting, hospitality, real estate, advisory, and asset management. Designed for *compound value* over decades, not quarters.",
      primary: "Explore Our Sectors",
      secondary: "Download Profile",
      metaLabel: "— At a Glance",
      stats: [
        { num: "2007", symbol: "", label: "Year\nFounded" },
        { num: "18", symbol: "+", label: "Years\nOperating" },
        { num: "05", symbol: "", label: "Active\nSectors" },
      ],
    },
    about: {
      markerNum: "01",
      markerLabel: "About Natwan",
      heading: "An entity built on *vision.*\nLed by execution.",
      lede: "An integrated investment platform spanning five interconnected sectors — designed for compound value over decades, not quarters.",
      meta: [
        { label: "Founded", value: "2007" },
        { label: "Sectors", value: "5 Active" },
        { label: "Headquarters", value: "Riyadh, KSA" },
        { label: "Structure", value: "Holding" },
      ],
      lead: "Natwan Group is more than a collection of companies. It is a *coordinated operating system for opportunity* — bringing strategy, market knowledge, and disciplined execution under one roof.",
      paras: [
        "We operate across vital sectors with one clear objective: to create real, sustainable value for our clients and partners. Our solutions rest on a deep reading of the market and a precise understanding of where opportunity lies.",
        "Through this approach, Natwan Group has established itself as a trusted partner — capable of converting challenges into opportunity, and ideas into projects that endure. Success, for us, is not the delivery of isolated services; it is an integrated system that moves with vision and produces measurable outcomes.",
      ],
      pullquote: {
        text: "At Natwan, we do not rely on improvisation. We rely on methodology — analysis, planning, and execution that compound into outcomes designed to last.",
        attr: "— Operating Philosophy · 2007",
      },
      feature: {
        quote: '"Like mountains, we are built to stand — through cycles, through transformation, through time."',
        tag: "FIG. 01\nFOUNDATION",
      },
    },
    values: {
      markerNum: "02",
      markerLabel: "Our Values",
      heading: "Not principles we declare.\n*Standards we operate by.*",
      aside: "Five values that shape every decision — from how we evaluate opportunities to how we deliver on commitments. They are not aspirational; they are operational.",
      cells: [
        { num: "/ 01", title: "Excellence", desc: "The highest standards of quality across everything we deliver." },
        { num: "/ 02", title: "Integrity", desc: "Trust built on transparency, clarity, and consistency." },
        { num: "/ 03", title: "Innovation", desc: "Solutions that move with the market — not behind it." },
        { num: "/ 04", title: "Commitment", desc: "Promises kept with precision, professionalism, and discipline." },
        { num: "/ 05", title: "Partnership", desc: "Long-term relationships — not single transactions." },
      ],
    },
    sectors: {
      heading: "Five sectors.\n*One operating philosophy.*",
      markerNum: "03",
      markerLabel: "What We Do",
      indexLabel: "Sector",
      aside: "Diversification led by integration — sectors that strengthen each other and create compounding advantages over the long term, rather than isolated lines of business.",
      items: [
        {
          num: "01", tag: "Build with confidence", title: "Contracting",
          quote: '"We build with confidence — to standards that hold."',
          desc: "Integrated construction services delivered to the highest quality and efficiency standards, with strict adherence to project timelines and specifications.",
          features: ["Project management & execution", "Quality assurance frameworks", "Schedule & cost discipline", "Safety & compliance protocols"],
          link: "Explore Contracting", tagText: "SECTOR 01 — CONTRACTING",
          image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        },
        {
          num: "02", tag: "A higher standard of stay", title: "Hospitality\n& Hotel Apartments",
          quote: '"A stay experience — to a higher standard."',
          desc: "Development and operation of hospitality and hotel apartment projects, focused on comfort, refined service, and the details that create real difference.",
          features: ["End-to-end property development", "Operational excellence in service", "Refined interior & guest experience", "Long-stay & corporate residency"],
          link: "Explore Hospitality", tagText: "SECTOR 02 — HOSPITALITY", reverse: true,
          image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        },
        {
          num: "03", tag: "Built on solid ground", title: "Investment\n& Real Estate Development",
          quote: '"Toward opportunities built on solid ground."',
          desc: "End-to-end solutions in real estate investment — from opportunity analysis and feasibility studies through planning, development, and project management.",
          features: ["Feasibility & due diligence", "Master planning & development", "Long-term asset stewardship", "Mixed-use & residential"],
          link: "Explore Real Estate", tagText: "SECTOR 03 — REAL ESTATE",
          image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        },
        {
          num: "04", tag: "Smarter, sharper decisions", title: "Advisory\n& Business Management",
          quote: '"Smarter decisions — for stronger businesses."',
          desc: "Specialised advisory services helping companies refine performance, sharpen strategy, and make decisions grounded in precise analysis rather than instinct.",
          features: ["Strategic planning & growth", "Operational optimisation", "Performance consulting", "Market entry & expansion"],
          link: "Explore Advisory", tagText: "SECTOR 04 — ADVISORY", reverse: true,
          image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        },
        {
          num: "05", tag: "Managing value, growing returns", title: "Asset\n& Investment Management",
          quote: '"We manage value — and grow returns."',
          desc: "Asset management services delivered through carefully studied strategies designed to maximise returns and minimise risk over the long term.",
          features: ["Portfolio construction", "Risk-adjusted return strategies", "Long-term capital preservation", "Diversified asset allocation"],
          link: "Explore Asset Management", tagText: "SECTOR 05 — ASSET MANAGEMENT",
          image: assetManagementImage,
        },
      ],
    },
    method: {
      markerNum: "04",
      markerLabel: "Our Methodology",
      heading: "Every step measured.\n*Every outcome earned.*",
      aside: "A repeatable, disciplined process applied across every engagement — from contracting projects to advisory mandates. Methodology is not bureaucracy; it is the difference between aspiration and outcome.",
      rows: [
        { num: "01.", title: "Analyse & Understand", desc: "Studying the client's needs and the surrounding market with precision and patience." },
        { num: "02.", title: "Strategise", desc: "A clear plan built on objectives that are ambitious, measurable, and reachable." },
        { num: "03.", title: "Execute", desc: "Projects delivered to the highest professional standards — without compromise." },
        { num: "04.", title: "Refine", desc: "Continuous performance monitoring and refinement as the engagement progresses." },
        { num: "05.", title: "Endure", desc: "Outcomes designed to compound and last — not merely to launch and announce.", star: true },
      ],
    },
    portfolio: {
      heading: "Built across *sectors.*\nConnected by *standard.*",
      markerNum: "05",
      markerLabel: "Selected Work",
      aside: "A selection of projects across our active sectors — each a reflection of the same commitment to quality, methodology, and outcomes that endure.",
      cards: [
        { tag: "Real Estate", num: "01.", title: "Mixed-Use Tower\nDevelopment", location: "RIYADH · 2024", tall: true, image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85" },
        { tag: "Hospitality", num: "02.", title: "Hotel Apartments\nComplex", location: "JEDDAH · 2023", image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85" },
        { tag: "Contracting", num: "03.", title: "Commercial\nBuild-Out", location: "RIYADH · 2024", image: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85" },
        { tag: "Advisory", num: "04.", title: "Strategy &\nTransformation", location: "CONFIDENTIAL · 2023", image: "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85" },
        { tag: "Asset Mgmt.", num: "05.", title: "Portfolio\nDiversification", location: "REGIONAL · ONGOING", image: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85" },
      ],
      cta: "View Full Project Portfolio",
    },
    why: {
      markerNum: "06",
      markerLabel: "Why Natwan",
      heading: "The right choice begins\nwith a *partner you can rely on.*",
      aside: "Choosing Natwan is not choosing a service — it is choosing a long-term partner whose interests are aligned with your outcomes, not your transactions.",
      cells: [
        { num: "01.", title: "18+ Years of Experience", desc: "Operating in the market since 2007, with understanding shaped by complete economic cycles — not one moment in time." },
        { num: "02.", title: "Integrated Solutions", desc: "Multiple services under one umbrella, designed to compound capability rather than fragment it across vendors." },
        { num: "03.", title: "Strong Market Expertise", desc: "Deep understanding of local and regional markets — and of the people, institutions, and dynamics that shape them." },
        { num: "04.", title: "High Execution Quality", desc: "Full commitment to the highest standards from initiation through completion — every project, every time." },
        { num: "05.", title: "Results-Focused", desc: "Tangible, measurable outcomes — not promises, presentations, or progress reports without progress." },
        { num: "06.", title: "Long-Term Partnerships", desc: "Relationships built on trust and designed to last beyond any single project or engagement." },
      ],
    },
    vision: {
      markerNum: "07",
      markerLabel: "Saudi Vision 2030",
      heading: "Part of a *vision.*\nShaping its impact today.",
      body: "At Natwan, we do not simply keep pace with national transformation — we participate in shaping it. Our investments and projects are deliberately aligned with the goals of Saudi Vision 2030: building businesses that contribute to a more diverse, sustainable, and elevated economy.",
      pillars: [
        { num: "Pillar 01", name: "Economic Diversification" },
        { num: "Pillar 02", name: "Sustainability" },
        { num: "Pillar 03", name: "Quality of Life" },
      ],
      corner: "Aligned with the Kingdom",
    },
    chairman: {
      markerNum: "08",
      markerLabel: "Chairman's Message",
      portraitTag: "— Chairman's Office",
      heading: "A vision that *inspires.*\nLeadership that makes the difference.",
      quote: '"We built Natwan on foundations that combine *strategic clarity* with *professional execution* — a model that reflects quality, trust, and sustainability across everything we do. Our work is shaped by patience, our standards by experience, and our partnerships by the conviction that lasting value is earned, not promised."',
      sigName: "[ Chairman's Name ]",
      sigTitle: "Chairman of the Board · Natwan Group",
    },
    contact: {
      markerNum: "09",
      markerLabel: "Get in Touch",
      heading: "Let's build\nsomething *that lasts.*",
      body: "Whether you're exploring a partnership, an investment opportunity, or a service engagement — we would be glad to start the conversation.",
      cta: "Schedule a Meeting",
      rows: [
        { label: "Email", value: "info@natwanco.com", href: "mailto:info@natwanco.com" },
        { label: "Phone", value: "+966 54 200 8206", href: "tel:+966542008206" },
        { label: "WhatsApp", value: "+966 54 200 8206", href: "https://wa.me/966542008206" },
        { label: "Address", value: "Riyadh, Kingdom of Saudi Arabia" },
        { label: "Hours", value: "Sun–Thu · 09:00 – 17:00 AST" },
      ],
    },
  },

  ar: {
    hero: {
      eyebrow: "مجموعة استثمارية متنوّعة · تأسست 2007",
      title: ["نبني", "ما", "يدوم."],
      lede: "تعمل مجموعة نطوان عبر خمسة قطاعات متكاملة — المقاولات والضيافة والعقارات والاستشارات وإدارة الأصول. مصمَّمة من أجل *قيمة تراكمية* تمتد لعقود، لا لأرباع سنوية.",
      primary: "استكشف قطاعاتنا",
      secondary: "تحميل الملف التعريفي",
      metaLabel: "— لمحة سريعة",
      stats: [
        { num: "2007", symbol: "", label: "سنة\nالتأسيس" },
        { num: "18", symbol: "+", label: "عاماً\nمن العمل" },
        { num: "05", symbol: "", label: "قطاعات\nنشطة" },
      ],
    },
    about: {
      markerNum: "01",
      markerLabel: "عن نطوان",
      heading: "كيانٌ مبنيّ على *الرؤية.*\nتقوده القدرة على التنفيذ.",
      lede: "منصّة استثمارية متكاملة تمتد عبر خمسة قطاعات مترابطة — مصمّمة لقيمة تراكمية تمتد لعقود لا لأرباع سنوية.",
      meta: [
        { label: "التأسيس", value: "2007" },
        { label: "القطاعات", value: "5 نشطة" },
        { label: "المقر الرئيسي", value: "الرياض، السعودية" },
        { label: "البنية", value: "قابضة" },
      ],
      lead: "مجموعة نطوان أكثر من مجرّد مجموعة شركات؛ إنها *منظومة تشغيلية منسّقة للفرص* — تجمع الاستراتيجية ومعرفة السوق والتنفيذ المنضبط تحت سقف واحد.",
      paras: [
        "نعمل عبر قطاعات حيوية بهدفٍ واضح واحد: خلق قيمة حقيقية ومستدامة لعملائنا وشركائنا. ترتكز حلولنا على قراءة عميقة للسوق وفهمٍ دقيق لمواطن الفرص.",
        "من خلال هذا النهج، رسّخت مجموعة نطوان مكانتها كشريك موثوق — قادر على تحويل التحديات إلى فرص، والأفكار إلى مشاريع تدوم. النجاح بالنسبة لنا ليس تقديم خدمات منفصلة، بل منظومة متكاملة تتحرّك برؤية وتُنتج نتائج قابلة للقياس.",
      ],
      pullquote: {
        text: "في نطوان لا نعتمد على الارتجال، بل على المنهجية — التحليل والتخطيط والتنفيذ الذي يتراكم ليُثمر نتائج صُمّمت لتبقى.",
        attr: "— فلسفة التشغيل · 2007",
      },
      feature: {
        quote: "«كالجبال، خُلقنا لنصمد — عبر الدورات، وعبر التحوّلات، وعبر الزمن.»",
        tag: "شكل 01\nالأساس",
      },
    },
    values: {
      markerNum: "02",
      markerLabel: "قيمنا",
      heading: "ليست مبادئ نعلنها.\n*بل معايير نعمل بها.*",
      aside: "خمس قيم تُشكّل كل قرار — من كيفية تقييمنا للفرص إلى كيفية وفائنا بالتزاماتنا. إنها ليست طموحات؛ بل ممارسات تشغيلية.",
      cells: [
        { num: "/ 01", title: "التميّز", desc: "أعلى معايير الجودة في كل ما نقدّمه." },
        { num: "/ 02", title: "النزاهة", desc: "ثقة مبنيّة على الشفافية والوضوح والاتساق." },
        { num: "/ 03", title: "الابتكار", desc: "حلول تتحرّك مع السوق — لا خلفه." },
        { num: "/ 04", title: "الالتزام", desc: "وعود تُنجَز بدقّة واحترافية وانضباط." },
        { num: "/ 05", title: "الشراكة", desc: "علاقات طويلة الأمد — لا صفقات عابرة." },
      ],
    },
    sectors: {
      heading: "خمسة قطاعات.\n*فلسفة تشغيل واحدة.*",
      markerNum: "03",
      markerLabel: "ما نقوم به",
      indexLabel: "قطاع",
      aside: "تنوّعٌ يقوده التكامل — قطاعات يعزّز بعضها بعضاً وتُنشئ مزايا تراكمية على المدى الطويل، بدلاً من خطوط أعمال منعزلة.",
      items: [
        {
          num: "01", tag: "نبني بثقة", title: "المقاولات",
          quote: "«نبني بثقة — وفق معايير تصمد.»",
          desc: "خدمات إنشاء متكاملة تُقدَّم وفق أعلى معايير الجودة والكفاءة، مع التزام صارم بمواعيد المشاريع ومواصفاتها.",
          features: ["إدارة وتنفيذ المشاريع", "أطر ضمان الجودة", "انضباط الجدول والتكلفة", "بروتوكولات السلامة والامتثال"],
          link: "استكشف المقاولات", tagText: "القطاع 01 — المقاولات",
          image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        },
        {
          num: "02", tag: "معيار أرقى للإقامة", title: "الضيافة\nوالشقق الفندقية",
          quote: "«تجربة إقامة — بمعيار أرقى.»",
          desc: "تطوير وتشغيل مشاريع الضيافة والشقق الفندقية، مع التركيز على الراحة والخدمة الراقية والتفاصيل التي تصنع فرقاً حقيقياً.",
          features: ["تطوير عقاري شامل", "تميّز تشغيلي في الخدمة", "تصميم داخلي راقٍ وتجربة ضيوف", "إقامة طويلة وسكن للشركات"],
          link: "استكشف الضيافة", tagText: "القطاع 02 — الضيافة", reverse: true,
          image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        },
        {
          num: "03", tag: "على أرضٍ صلبة", title: "الاستثمار\nوالتطوير العقاري",
          quote: "«نحو فرصٍ مبنيّة على أرضٍ صلبة.»",
          desc: "حلول شاملة في الاستثمار العقاري — من تحليل الفرص ودراسات الجدوى مروراً بالتخطيط والتطوير وحتى إدارة المشاريع.",
          features: ["دراسات الجدوى والعناية الواجبة", "التخطيط الرئيسي والتطوير", "إدارة الأصول طويلة الأمد", "الاستخدام المختلط والسكني"],
          link: "استكشف العقارات", tagText: "القطاع 03 — العقارات",
          image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        },
        {
          num: "04", tag: "قرارات أذكى وأدقّ", title: "الاستشارات\nوإدارة الأعمال",
          quote: "«قرارات أذكى — لأعمالٍ أقوى.»",
          desc: "خدمات استشارية متخصّصة تساعد الشركات على تطوير أدائها وصقل استراتيجياتها واتخاذ قرارات مبنيّة على تحليل دقيق لا على الحدس.",
          features: ["التخطيط الاستراتيجي والنمو", "تحسين العمليات", "استشارات الأداء", "دخول الأسواق والتوسّع"],
          link: "استكشف الاستشارات", tagText: "القطاع 04 — الاستشارات", reverse: true,
          image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        },
        {
          num: "05", tag: "إدارة القيمة وتنمية العوائد", title: "إدارة الأصول\nوالاستثمار",
          quote: "«ندير القيمة — وننمّي العوائد.»",
          desc: "خدمات إدارة أصول تُقدَّم عبر استراتيجيات مدروسة بعناية تهدف إلى تعظيم العوائد وتقليل المخاطر على المدى الطويل.",
          features: ["بناء المحافظ الاستثمارية", "استراتيجيات عوائد معدّلة بالمخاطر", "الحفاظ على رأس المال طويل الأمد", "توزيع أصول متنوّع"],
          link: "استكشف إدارة الأصول", tagText: "القطاع 05 — إدارة الأصول",
          image: assetManagementImage,
        },
      ],
    },
    method: {
      markerNum: "04",
      markerLabel: "منهجيتنا",
      heading: "كل خطوة مدروسة.\n*وكل نتيجة مستحَقّة.*",
      aside: "عملية منضبطة وقابلة للتكرار تُطبَّق في كل ارتباط — من مشاريع المقاولات إلى مهام الاستشارات. المنهجية ليست بيروقراطية؛ إنها الفارق بين الطموح والنتيجة.",
      rows: [
        { num: "01.", title: "التحليل والفهم", desc: "دراسة احتياجات العميل والسوق المحيط بدقّة وصبر." },
        { num: "02.", title: "وضع الاستراتيجية", desc: "خطة واضحة مبنيّة على أهداف طموحة وقابلة للقياس والتحقيق." },
        { num: "03.", title: "التنفيذ", desc: "مشاريع تُنجَز وفق أعلى المعايير المهنية — دون تنازل." },
        { num: "04.", title: "التحسين", desc: "مراقبة مستمرة للأداء وتحسينه مع تقدّم العمل." },
        { num: "05.", title: "الاستدامة", desc: "نتائج صُمّمت لتتراكم وتدوم — لا لمجرّد الإطلاق والإعلان.", star: true },
      ],
    },
    portfolio: {
      heading: "بُنيت عبر *القطاعات.*\nيربطها *المعيار.*",
      markerNum: "05",
      markerLabel: "أعمال مختارة",
      aside: "مجموعة مختارة من المشاريع عبر قطاعاتنا النشطة — كلٌّ منها انعكاس للالتزام نفسه بالجودة والمنهجية والنتائج التي تدوم.",
      cards: [
        { tag: "العقارات", num: "01.", title: "برج متعدّد\nالاستخدامات", location: "الرياض · 2024", tall: true, image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85" },
        { tag: "الضيافة", num: "02.", title: "مجمّع شقق\nفندقية", location: "جدة · 2023", image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85" },
        { tag: "المقاولات", num: "03.", title: "تجهيز مبنى\nتجاري", location: "الرياض · 2024", image: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85" },
        { tag: "الاستشارات", num: "04.", title: "استراتيجية\nوتحوّل", location: "سرّي · 2023", image: "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85" },
        { tag: "إدارة الأصول", num: "05.", title: "تنويع\nالمحفظة", location: "إقليمي · مستمر", image: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85" },
      ],
      cta: "عرض كامل سجلّ المشاريع",
    },
    why: {
      markerNum: "06",
      markerLabel: "لماذا نطوان",
      heading: "الخيار الصائب يبدأ\nبـ *شريكٍ يُعتمَد عليه.*",
      aside: "اختيار نطوان ليس اختيار خدمة — بل اختيار شريك طويل الأمد تتوافق مصالحه مع نتائجك، لا مع صفقاتك.",
      cells: [
        { num: "01.", title: "خبرة تتجاوز 18 عاماً", desc: "نعمل في السوق منذ 2007، بفهمٍ صاغته دورات اقتصادية كاملة — لا لحظة واحدة." },
        { num: "02.", title: "حلول متكاملة", desc: "خدمات متعدّدة تحت مظلة واحدة، مصمّمة لتراكم القدرات بدلاً من تشتيتها بين موردين." },
        { num: "03.", title: "خبرة سوقية قوية", desc: "فهم عميق للأسواق المحلية والإقليمية — وللأشخاص والمؤسسات والديناميكيات التي تشكّلها." },
        { num: "04.", title: "جودة تنفيذ عالية", desc: "التزام كامل بأعلى المعايير من البداية حتى الإنجاز — في كل مشروع وفي كل مرّة." },
        { num: "05.", title: "تركيز على النتائج", desc: "نتائج ملموسة وقابلة للقياس — لا وعود ولا عروض ولا تقارير تقدّم بلا تقدّم." },
        { num: "06.", title: "شراكات طويلة الأمد", desc: "علاقات مبنيّة على الثقة ومصمّمة لتدوم أبعد من أي مشروع أو ارتباط منفرد." },
      ],
    },
    vision: {
      markerNum: "07",
      markerLabel: "رؤية السعودية 2030",
      heading: "جزءٌ من *رؤية.*\nنصنع أثرها اليوم.",
      body: "في نطوان لا نكتفي بمواكبة التحوّل الوطني — بل نشارك في صياغته. استثماراتنا ومشاريعنا متوائمة عن قصد مع أهداف رؤية السعودية 2030: بناء أعمال تُسهم في اقتصاد أكثر تنوّعاً واستدامةً ورُقيّاً.",
      pillars: [
        { num: "الركيزة 01", name: "التنويع الاقتصادي" },
        { num: "الركيزة 02", name: "الاستدامة" },
        { num: "الركيزة 03", name: "جودة الحياة" },
      ],
      corner: "متوائمون مع المملكة",
    },
    chairman: {
      markerNum: "08",
      markerLabel: "كلمة رئيس مجلس الإدارة",
      portraitTag: "— مكتب رئيس مجلس الإدارة",
      heading: "رؤيةٌ *تُلهِم.*\nوقيادةٌ تصنع الفرق.",
      quote: "«بنينا نطوان على أسسٍ تجمع *الوضوح الاستراتيجي* مع *التنفيذ المهني* — نموذج يعكس الجودة والثقة والاستدامة في كل ما نقوم به. عملنا يصوغه الصبر، ومعاييرنا تصوغها الخبرة، وشراكاتنا يصوغها الإيمان بأن القيمة الدائمة تُكتسَب ولا تُوعَد بها.»",
      sigName: "[ اسم رئيس مجلس الإدارة ]",
      sigTitle: "رئيس مجلس الإدارة · مجموعة نطوان",
    },
    contact: {
      markerNum: "09",
      markerLabel: "تواصل معنا",
      heading: "لنبنِ معاً\nشيئاً *يدوم.*",
      body: "سواء كنت تستكشف شراكة، أو فرصة استثمارية، أو ارتباط خدمة — يسعدنا أن نبدأ الحوار.",
      cta: "احجز اجتماعاً",
      rows: [
        { label: "البريد الإلكتروني", value: "info@natwanco.com", href: "mailto:info@natwanco.com" },
        { label: "الهاتف", value: "+966 54 200 8206", href: "tel:+966542008206" },
        { label: "واتساب", value: "+966 54 200 8206", href: "https://wa.me/966542008206" },
        { label: "العنوان", value: "الرياض، المملكة العربية السعودية" },
        { label: "ساعات العمل", value: "الأحد–الخميس · 09:00 – 17:00 بتوقيت السعودية" },
      ],
    },
  },
};
