// Projects page copy in EN + AR. Each project's `key` maps to an image
// collection in src/lib/galleryImages.js; the page pulls the photos from there.
export const projects = {
  en: {
    crumb: "Projects",
    hero: {
      eyebrow: "◆ SELECTED WORK · BUILT TO ENDURE",
      title: ["The work,", "and the ground it *stands on.*"],
      lede: "A look at what we've built and operated across our sectors — projects judged not by how they photograph, but by how they hold up over time.",
      meta: [
        { label: "Since", value: "2007" },
        { label: "Sectors", value: "Five" },
        { label: "Headquarters", value: "Dammam" },
        { label: "Principle", value: "Built to last" },
      ],
    },
    intro: {
      label: "— ON OUR\nWORK",
      statement: "Every project carries our name — so every project is held to the same standard: *executed with care, delivered on its promise.*",
    },
    factLabels: { sector: "Sector", location: "Location", year: "Year" },
    framesLabel: "Frames",
    items: [
      {
        key: "abha",
        num: "01.",
        idLabel: "PROJECT 01",
        title: "Natwan Abha",
        sector: "Hospitality · Real Estate",
        location: "Abha · 'Asir",
        year: "2024",
        body: "A hospitality and residential development set against the highlands of 'Asir — where elevation, climate, and craft come together. Natwan Abha reflects our conviction that a building should belong to its place, not merely sit on it.",
      },
      {
        key: "cafe",
        num: "02.",
        idLabel: "PROJECT 02",
        title: "Masa'at Café & Restaurant",
        sector: "Hospitality · F&B",
        location: "Dammam",
        year: "2022",
        body: "An intimate café concept — designed, built, and fitted out in-house. Warm materials, considered light, and a calm that quietly invites people to stay a little longer.",
      },
      {
        key: "contracting",
        num: "03.",
        idLabel: "PROJECT 03",
        title: "Contracting Works",
        sector: "Contracting",
        location: "Kingdom-wide",
        year: "2023 — Present",
        body: "Structure, execution, and finishing across a range of contracts — delivered to specification, on schedule, and to a standard of finish that holds up close. The quiet discipline behind everything we build.",
      },
      {
        key: "projects",
        num: "04.",
        idLabel: "PROJECT 04",
        title: "Recent Developments",
        sector: "Development",
        location: "Dammam",
        year: "2025",
        body: "A selection of recent works in progress — each one a continuation of the same idea we started with: build what endures.",
      },
    ],
    closing: {
      eyebrow: "◆ YOUR PROJECT, NEXT",
      heading: "Have something you want *built to last?*",
      body: "From first study to final handover, we bring one standard to every stage. Tell us what you're planning.",
      cta: "Start a Conversation",
    },
  },

  ar: {
    crumb: "مشاريعنا",
    hero: {
      eyebrow: "◆ أعمال مختارة · بُنيت لتدوم",
      title: ["العمل,", "والأرض التي *يقوم عليها.*"],
      lede: "نظرة على ما بنيناه وشغّلناه عبر قطاعاتنا — مشاريع لا تُقاس بجمال صورها، بل بقدرتها على الصمود مع الوقت.",
      meta: [
        { label: "منذ", value: "2007" },
        { label: "القطاعات", value: "خمسة" },
        { label: "المقر الرئيسي", value: "الدمام" },
        { label: "المبدأ", value: "بُني ليدوم" },
      ],
    },
    intro: {
      label: "— عن\nأعمالنا",
      statement: "كل مشروع يحمل اسمنا — لذا يخضع كل مشروع للمعيار ذاته: *يُنفَّذ بعناية، ويُسلَّم بوفاءٍ لوعده.*",
    },
    factLabels: { sector: "القطاع", location: "الموقع", year: "السنة" },
    framesLabel: "لقطة",
    items: [
      {
        key: "abha",
        num: "01.",
        idLabel: "مشروع 01",
        title: "نطوان أبها",
        sector: "الضيافة · العقارات",
        location: "أبها · عسير",
        year: "2024",
        body: "مشروع ضيافة وسكني يتّكئ على مرتفعات عسير — حيث يجتمع الارتفاع والمناخ والحِرفة. تعكس نطوان أبها قناعتنا بأن المبنى ينبغي أن ينتمي إلى مكانه، لا أن يحلّ عليه فحسب.",
      },
      {
        key: "cafe",
        num: "02.",
        idLabel: "مشروع 02",
        title: "مقهى ومطعم مساءات",
        sector: "الضيافة · الأغذية والمشروبات",
        location: "الدمام",
        year: "2022",
        body: "مقهى بطابع حميم — صُمّم ونُفّذ وجُهّز داخلياً بالكامل. خامات دافئة، وإضاءة مدروسة، وهدوءٌ يدعو الناس بلطف إلى البقاء وقتاً أطول.",
      },
      {
        key: "contracting",
        num: "03.",
        idLabel: "مشروع 03",
        title: "أعمال المقاولات",
        sector: "المقاولات",
        location: "على مستوى المملكة",
        year: "2023 — حتى الآن",
        body: "هيكلٌ وتنفيذٌ وتشطيبٌ عبر مجموعة من العقود — تُسلَّم وفق المواصفات، وفي مواعيدها، وبمستوى إنجازٍ يصمد عند التدقيق. هو الانضباط الهادئ خلف كل ما نبنيه.",
      },
      {
        key: "projects",
        num: "04.",
        idLabel: "مشروع 04",
        title: "أعمال حديثة",
        sector: "التطوير",
        location: "الدمام",
        year: "2025",
        body: "مجموعة مختارة من الأعمال قيد الإنجاز — كلٌّ منها امتدادٌ للفكرة ذاتها التي بدأنا بها: نبني ما يدوم.",
      },
    ],
    closing: {
      eyebrow: "◆ مشروعك، تالياً",
      heading: "لديك ما تريده *مبنيّاً ليدوم؟*",
      body: "من الدراسة الأولى إلى التسليم النهائي، نحمل معياراً واحداً في كل مرحلة. حدّثنا عمّا تخطّط له.",
      cta: "ابدأ حواراً",
    },
  },
};
