export const sectors = {
  en: {
    crumb: "Sectors",
    hero: {
      eyebrow: "◆ OUR SERVICES · SECTION 08",
      title: ["Diversity", "led by *integration.*"],
      tagline: "Results built on consistency.",
      lede: "Natwan Group operates through a set of integrated sectors that support one another — designed to deliver comprehensive solutions across the varied needs of our clients.",
      nav: [
        { num: "01.", name: "Contracting", to: "sector-01" },
        { num: "02.", name: "Hospitality", to: "sector-02" },
        { num: "03.", name: "Real Estate", to: "sector-03" },
        { num: "04.", name: "Advisory", to: "sector-04" },
        { num: "05.", name: "Asset Mgmt.", to: "sector-05" },
      ],
    },
    intro: {
      label: "— ON OUR\nSECTORS",
      statement: "Natwan Group operates through a set of *integrated sectors* that support one another — with the aim of delivering comprehensive solutions that cover the varied needs of our clients.",
    },
    s01: {
      idLabel: "SECTOR 01", num: "01.",
      title: "Contracting",
      tagline: "We build with confidence — and execute to standards that hold.",
      body: "Natwan Group provides integrated contracting services, including project execution to the highest quality and efficiency standards — with precise adherence to timelines and project requirements.",
      imageTag: "— FIG. I / CONTRACTING",
      image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
    },
    s02: {
      idLabel: "SECTOR 02", num: "02.",
      title: "Hospitality &\n*Hotel Apartments*",
      tagline: "A stay experience — at a higher standard.",
      body: "We develop and operate hospitality and hotel apartment projects to the highest quality standards — focused on delivering an integrated experience that brings together comfort, refined service, and the details that make the difference.",
      metaQuote: "The details that make the difference are the ones our guests carry with them long after they leave.",
    },
    s03: {
      idLabel: "SECTOR 03", num: "03.",
      title: "Investment & *Real Estate Development.*",
      tagline: "Toward opportunities built on solid ground.",
      metaAccent: "— Practice III",
      metaLines: "End-to-End\nReal Estate\nSolutions",
      body: "We provide integrated solutions in the field of investment and real estate development — beginning with opportunity study and feasibility analysis, progressing through planning and development, and extending to execution and project management.",
      images: [
        "https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85",
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        "https://images.unsplash.com/photo-1487958449943-2429e8be8625?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85",
      ],
    },
    s04: {
      idLabel: "SECTOR 04", num: "04.",
      title: "Advisory & *Business Management.*",
      taglineLabel: "— On Advisory",
      taglineText: '"Smarter decisions — for stronger businesses."',
      body: "We provide specialised advisory services that help companies *develop their performance,* refine their strategies, and make decisions built on precise analysis.",
    },
    s05: {
      idLabel: "SECTOR 05", num: "05.",
      tagline: "We manage value — and grow returns.",
      title: "Asset & *Investment Management.*",
      body: "We provide asset and investment management services through carefully studied strategies — designed to maximise returns and minimise risk.",
    },
    closing: {
      eyebrow: "◆ ONE PHILOSOPHY · FIVE PRACTICES",
      heading: "Diversity led by *integration.*",
      body: "Each sector strengthens the others — creating an ecosystem of expertise that few standalone firms can match.",
      cta: "Start a Conversation",
    },
  },

  ar: {
    crumb: "قطاعاتنا",
    hero: {
      eyebrow: "◆ خدماتنا · القسم 08",
      title: ["تنوّعٌ", "يقوده *التكامل.*"],
      tagline: "نتائج مبنيّة على الاتساق.",
      lede: "تعمل مجموعة نطوان عبر منظومة من القطاعات المتكاملة التي يدعم بعضها بعضاً — مصمّمة لتقديم حلول شاملة تغطّي الاحتياجات المتنوّعة لعملائنا.",
      nav: [
        { num: "01.", name: "المقاولات", to: "sector-01" },
        { num: "02.", name: "الضيافة", to: "sector-02" },
        { num: "03.", name: "العقارات", to: "sector-03" },
        { num: "04.", name: "الاستشارات", to: "sector-04" },
        { num: "05.", name: "إدارة الأصول", to: "sector-05" },
      ],
    },
    intro: {
      label: "— عن\nقطاعاتنا",
      statement: "تعمل مجموعة نطوان عبر منظومة من *القطاعات المتكاملة* التي يدعم بعضها بعضاً — بهدف تقديم حلول شاملة تغطّي الاحتياجات المتنوّعة لعملائنا.",
    },
    s01: {
      idLabel: "القطاع 01", num: "01.",
      title: "المقاولات",
      tagline: "نبني بثقة — وننفّذ وفق معايير تصمد.",
      body: "تقدّم مجموعة نطوان خدمات مقاولات متكاملة، تشمل تنفيذ المشاريع وفق أعلى معايير الجودة والكفاءة — مع التزام دقيق بالمواعيد ومتطلّبات المشروع.",
      imageTag: "— شكل I / المقاولات",
      image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
    },
    s02: {
      idLabel: "القطاع 02", num: "02.",
      title: "الضيافة\n*والشقق الفندقية*",
      tagline: "تجربة إقامة — بمعيار أرقى.",
      body: "نطوّر ونشغّل مشاريع الضيافة والشقق الفندقية وفق أعلى معايير الجودة — مع التركيز على تقديم تجربة متكاملة تجمع الراحة والخدمة الراقية والتفاصيل التي تصنع الفرق.",
      metaQuote: "التفاصيل التي تصنع الفرق هي تلك التي يحملها ضيوفنا معهم طويلاً بعد مغادرتهم.",
    },
    s03: {
      idLabel: "القطاع 03", num: "03.",
      title: "الاستثمار *والتطوير العقاري.*",
      tagline: "نحو فرصٍ مبنيّة على أرضٍ صلبة.",
      metaAccent: "— الممارسة III",
      metaLines: "حلول عقارية\nمتكاملة\nمن الألف إلى الياء",
      body: "نقدّم حلولاً متكاملة في مجال الاستثمار والتطوير العقاري — بدءاً من دراسة الفرص وتحليل الجدوى، مروراً بالتخطيط والتطوير، وصولاً إلى التنفيذ وإدارة المشاريع.",
      images: [
        "https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85",
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=1400&q=85",
        "https://images.unsplash.com/photo-1487958449943-2429e8be8625?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=85",
      ],
    },
    s04: {
      idLabel: "القطاع 04", num: "04.",
      title: "الاستشارات *وإدارة الأعمال.*",
      taglineLabel: "— عن الاستشارات",
      taglineText: "«قرارات أذكى — لأعمالٍ أقوى.»",
      body: "نقدّم خدمات استشارية متخصّصة تساعد الشركات على *تطوير أدائها,* وصقل استراتيجياتها، واتخاذ قرارات مبنيّة على تحليل دقيق.",
    },
    s05: {
      idLabel: "القطاع 05", num: "05.",
      tagline: "ندير القيمة — وننمّي العوائد.",
      title: "إدارة الأصول *والاستثمار.*",
      body: "نقدّم خدمات إدارة الأصول والاستثمار عبر استراتيجيات مدروسة بعناية — مصمّمة لتعظيم العوائد وتقليل المخاطر.",
    },
    closing: {
      eyebrow: "◆ فلسفة واحدة · خمس ممارسات",
      heading: "تنوّعٌ يقوده *التكامل.*",
      body: "يعزّز كل قطاع القطاعات الأخرى — منشئاً منظومة من الخبرة يصعب على الشركات المنفردة مضاهاتها.",
      cta: "ابدأ حواراً",
    },
  },
};
